const I = (name: string) => `/mc-assets-main/item-assets/${name}.png`
const E = (name: string) => `/mc-assets-main/entity-assets/${name}.png`

export interface MCObjective {
  id: string
  label: string
  categoryHints: string[]
  icon: string
}

export const MC_OBJECTIVES: MCObjective[] = [
  // ── Kill ──────────────────────────────────────────────────────────────────
  { id: 'zombie',            label: 'Zombie',            categoryHints: ['kill'], icon: E('ZOMBIE') },
  { id: 'skeleton',          label: 'Skeleton',          categoryHints: ['kill'], icon: E('SKELETON') },
  { id: 'creeper',           label: 'Creeper',           categoryHints: ['kill'], icon: E('CREEPER') },
  { id: 'spider',            label: 'Spider',            categoryHints: ['kill'], icon: E('SPIDER') },
  { id: 'cave_spider',       label: 'Cave Spider',       categoryHints: ['kill'], icon: E('CAVE_SPIDER') },
  { id: 'enderman',          label: 'Enderman',          categoryHints: ['kill'], icon: E('ENDERMAN') },
  { id: 'blaze',             label: 'Blaze',             categoryHints: ['kill'], icon: E('BLAZE') },
  { id: 'witch',             label: 'Witch',             categoryHints: ['kill'], icon: E('WITCH') },
  { id: 'pillager',          label: 'Pillager',          categoryHints: ['kill'], icon: E('PILLAGER') },
  { id: 'vindicator',        label: 'Vindicator',        categoryHints: ['kill'], icon: E('VINDICATOR') },
  { id: 'ravager',           label: 'Ravager',           categoryHints: ['kill'], icon: E('RAVAGER') },
  { id: 'phantom',           label: 'Phantom',           categoryHints: ['kill'], icon: E('PHANTOM') },
  { id: 'drowned',           label: 'Drowned',           categoryHints: ['kill'], icon: E('DROWNED') },
  { id: 'husk',              label: 'Husk',              categoryHints: ['kill'], icon: E('HUSK') },
  { id: 'stray',             label: 'Stray',             categoryHints: ['kill'], icon: E('STRAY') },
  { id: 'wither_skeleton',   label: 'Wither Skeleton',   categoryHints: ['kill'], icon: E('WITHER_SKELETON') },
  { id: 'ghast',             label: 'Ghast',             categoryHints: ['kill'], icon: E('GHAST') },
  { id: 'magma_cube',        label: 'Magma Cube',        categoryHints: ['kill'], icon: E('MAGMA_CUBE') },
  { id: 'slime',             label: 'Slime',             categoryHints: ['kill'], icon: E('SLIME') },
  { id: 'guardian',          label: 'Guardian',          categoryHints: ['kill'], icon: E('GUARDIAN') },
  { id: 'elder_guardian',    label: 'Elder Guardian',    categoryHints: ['kill'], icon: E('ELDER_GUARDIAN') },
  { id: 'shulker',           label: 'Shulker',           categoryHints: ['kill'], icon: E('SHULKER') },
  { id: 'endermite',         label: 'Endermite',         categoryHints: ['kill'], icon: E('ENDERMITE') },
  { id: 'silverfish',        label: 'Silverfish',        categoryHints: ['kill'], icon: E('SILVERFISH') },
  { id: 'warden',            label: 'Warden',            categoryHints: ['kill'], icon: E('WARDEN') },
  { id: 'ender_dragon',      label: 'Ender Dragon',      categoryHints: ['kill'], icon: E('ENDER_DRAGON') },
  { id: 'wither',            label: 'Wither',            categoryHints: ['kill'], icon: E('WITHER') },
  { id: 'piglin_brute',      label: 'Piglin Brute',      categoryHints: ['kill'], icon: E('PIGLIN_BRUTE') },
  { id: 'hoglin',            label: 'Hoglin',            categoryHints: ['kill'], icon: E('HOGLIN') },
  { id: 'zoglin',            label: 'Zoglin',            categoryHints: ['kill'], icon: E('ZOGLIN') },
  { id: 'zombified_piglin',  label: 'Zombified Piglin',  categoryHints: ['kill'], icon: E('ZOMBIFIED_PIGLIN') },
  { id: 'bogged',            label: 'Bogged',            categoryHints: ['kill'], icon: E('BOGGED') },
  { id: 'breeze',            label: 'Breeze',            categoryHints: ['kill'], icon: E('BREEZE') },

  // ── Mine ──────────────────────────────────────────────────────────────────
  { id: 'stone',             label: 'Stone',             categoryHints: ['mine'], icon: I('STONE') },
  { id: 'cobblestone',       label: 'Cobblestone',       categoryHints: ['mine'], icon: I('COBBLESTONE') },
  { id: 'deepslate',         label: 'Deepslate',         categoryHints: ['mine'], icon: I('DEEPSLATE') },
  { id: 'coal_ore',          label: 'Coal Ore',          categoryHints: ['mine'], icon: I('COAL_ORE') },
  { id: 'iron_ore',          label: 'Iron Ore',          categoryHints: ['mine'], icon: I('IRON_ORE') },
  { id: 'gold_ore',          label: 'Gold Ore',          categoryHints: ['mine'], icon: I('GOLD_ORE') },
  { id: 'diamond_ore',       label: 'Diamond Ore',       categoryHints: ['mine'], icon: I('DIAMOND_ORE') },
  { id: 'emerald_ore',       label: 'Emerald Ore',       categoryHints: ['mine'], icon: I('EMERALD_ORE') },
  { id: 'lapis_ore',         label: 'Lapis Ore',         categoryHints: ['mine'], icon: I('LAPIS_ORE') },
  { id: 'redstone_ore',      label: 'Redstone Ore',      categoryHints: ['mine'], icon: I('REDSTONE_ORE') },
  { id: 'ancient_debris',    label: 'Ancient Debris',    categoryHints: ['mine'], icon: I('ANCIENT_DEBRIS') },
  { id: 'netherrack',        label: 'Netherrack',        categoryHints: ['mine'], icon: I('NETHERRACK') },
  { id: 'sand',              label: 'Sand',              categoryHints: ['mine'], icon: I('SAND') },
  { id: 'gravel',            label: 'Gravel',            categoryHints: ['mine'], icon: I('GRAVEL') },
  { id: 'dirt',              label: 'Dirt',              categoryHints: ['mine'], icon: I('DIRT') },
  { id: 'grass_block',       label: 'Grass Block',       categoryHints: ['mine'], icon: I('GRASS_BLOCK') },
  { id: 'oak_log',           label: 'Oak Log',           categoryHints: ['mine'], icon: I('OAK_LOG') },
  { id: 'birch_log',         label: 'Birch Log',         categoryHints: ['mine'], icon: I('BIRCH_LOG') },
  { id: 'spruce_log',        label: 'Spruce Log',        categoryHints: ['mine'], icon: I('SPRUCE_LOG') },
  { id: 'jungle_log',        label: 'Jungle Log',        categoryHints: ['mine'], icon: I('JUNGLE_LOG') },
  { id: 'acacia_log',        label: 'Acacia Log',        categoryHints: ['mine'], icon: I('ACACIA_LOG') },
  { id: 'dark_oak_log',      label: 'Dark Oak Log',      categoryHints: ['mine'], icon: I('DARK_OAK_LOG') },
  { id: 'mangrove_log',      label: 'Mangrove Log',      categoryHints: ['mine'], icon: I('MANGROVE_LOG') },
  { id: 'cherry_log',        label: 'Cherry Log',        categoryHints: ['mine'], icon: I('CHERRY_LOG') },
  { id: 'cherry_leaves',     label: 'Cherry Leaves',     categoryHints: ['mine'], icon: I('CHERRY_LEAVES') },
  { id: 'oak_leaves',        label: 'Oak Leaves',        categoryHints: ['mine'], icon: I('OAK_LEAVES') },
  { id: 'amethyst_cluster',  label: 'Amethyst Cluster',  categoryHints: ['mine'], icon: I('AMETHYST_CLUSTER') },
  { id: 'large_amethyst_bud',label: 'Large Amethyst Bud',categoryHints: ['mine'], icon: I('LARGE_AMETHYST_BUD') },
  { id: 'obsidian',          label: 'Obsidian',          categoryHints: ['mine'], icon: I('OBSIDIAN') },
  { id: 'ice',               label: 'Ice',               categoryHints: ['mine'], icon: I('ICE') },
  { id: 'packed_ice',        label: 'Packed Ice',        categoryHints: ['mine'], icon: I('PACKED_ICE') },
  { id: 'snow_block',        label: 'Snow Block',        categoryHints: ['mine'], icon: I('SNOW_BLOCK') },
  { id: 'terracotta',        label: 'Terracotta',        categoryHints: ['mine'], icon: I('TERRACOTTA') },
  { id: 'clay',              label: 'Clay',              categoryHints: ['mine'], icon: I('CLAY') },
  { id: 'mud',               label: 'Mud',               categoryHints: ['mine'], icon: I('MUD') },

  // ── Craft ─────────────────────────────────────────────────────────────────
  { id: 'crafting_table',    label: 'Crafting Table',    categoryHints: ['craft'], icon: I('CRAFTING_TABLE') },
  { id: 'chest',             label: 'Chest',             categoryHints: ['craft'], icon: I('CHEST') },
  { id: 'iron_sword',        label: 'Iron Sword',        categoryHints: ['craft'], icon: I('IRON_SWORD') },
  { id: 'diamond_sword',     label: 'Diamond Sword',     categoryHints: ['craft'], icon: I('DIAMOND_SWORD') },
  { id: 'iron_pickaxe',      label: 'Iron Pickaxe',      categoryHints: ['craft'], icon: I('IRON_PICKAXE') },
  { id: 'diamond_pickaxe',   label: 'Diamond Pickaxe',   categoryHints: ['craft'], icon: I('DIAMOND_PICKAXE') },
  { id: 'bow',               label: 'Bow',               categoryHints: ['craft'], icon: I('BOW') },
  { id: 'crossbow',          label: 'Crossbow',          categoryHints: ['craft'], icon: I('CROSSBOW') },
  { id: 'shield',            label: 'Shield',            categoryHints: ['craft'], icon: I('SHIELD') },
  { id: 'pumpkin_pie',       label: 'Pumpkin Pie',       categoryHints: ['craft'], icon: I('PUMPKIN_PIE') },
  { id: 'cake',              label: 'Cake',              categoryHints: ['craft'], icon: I('CAKE') },
  { id: 'bread',             label: 'Bread',             categoryHints: ['craft'], icon: I('BREAD') },
  { id: 'cookie',            label: 'Cookie',            categoryHints: ['craft'], icon: I('COOKIE') },
  { id: 'painting',          label: 'Painting',          categoryHints: ['craft'], icon: I('PAINTING') },
  { id: 'observer',          label: 'Observer',          categoryHints: ['craft'], icon: I('OBSERVER') },
  { id: 'piston',            label: 'Piston',            categoryHints: ['craft'], icon: I('PISTON') },
  { id: 'honeycomb_block',   label: 'Honeycomb Block',   categoryHints: ['craft'], icon: I('HONEYCOMB_BLOCK') },
  { id: 'rabbit_stew',       label: 'Rabbit Stew',       categoryHints: ['craft'], icon: I('RABBIT_STEW') },
  { id: 'bookshelf',         label: 'Bookshelf',         categoryHints: ['craft'], icon: I('BOOKSHELF') },
  { id: 'tnt',               label: 'TNT',               categoryHints: ['craft'], icon: I('TNT') },
  { id: 'lead',              label: 'Lead',              categoryHints: ['craft'], icon: I('LEAD') },

  // ── Cook ──────────────────────────────────────────────────────────────────
  { id: 'cooked_beef',       label: 'Cooked Beef',       categoryHints: ['cook'], icon: I('COOKED_BEEF') },
  { id: 'steak',             label: 'Steak',             categoryHints: ['cook'], icon: I('COOKED_BEEF') },
  { id: 'cooked_chicken',    label: 'Cooked Chicken',    categoryHints: ['cook'], icon: I('COOKED_CHICKEN') },
  { id: 'cooked_porkchop',   label: 'Cooked Porkchop',   categoryHints: ['cook'], icon: I('COOKED_PORKCHOP') },
  { id: 'cooked_mutton',     label: 'Cooked Mutton',     categoryHints: ['cook'], icon: I('COOKED_MUTTON') },
  { id: 'cooked_rabbit',     label: 'Cooked Rabbit',     categoryHints: ['cook'], icon: I('COOKED_RABBIT') },
  { id: 'cooked_salmon',     label: 'Cooked Salmon',     categoryHints: ['cook'], icon: I('COOKED_SALMON') },
  { id: 'cooked_cod',        label: 'Cooked Cod',        categoryHints: ['cook'], icon: I('COOKED_COD') },
  { id: 'baked_potato',      label: 'Baked Potato',      categoryHints: ['cook'], icon: I('BAKED_POTATO') },
  { id: 'iron_ingot',        label: 'Iron Ingot',        categoryHints: ['cook'], icon: I('IRON_INGOT') },
  { id: 'gold_ingot',        label: 'Gold Ingot',        categoryHints: ['cook'], icon: I('GOLD_INGOT') },
  { id: 'glass',             label: 'Glass',             categoryHints: ['cook'], icon: I('GLASS') },
  { id: 'smooth_stone',      label: 'Smooth Stone',      categoryHints: ['cook'], icon: I('SMOOTH_STONE') },
  { id: 'brick',             label: 'Brick',             categoryHints: ['cook'], icon: I('BRICK') },
  { id: 'charcoal',          label: 'Charcoal',          categoryHints: ['cook'], icon: I('CHARCOAL') },

  // ── Eat ───────────────────────────────────────────────────────────────────
  { id: 'apple',                    label: 'Apple',                    categoryHints: ['eat'], icon: I('APPLE') },
  { id: 'golden_apple',             label: 'Golden Apple',             categoryHints: ['eat'], icon: I('GOLDEN_APPLE') },
  { id: 'enchanted_golden_apple',   label: 'Enchanted Golden Apple',   categoryHints: ['eat'], icon: I('ENCHANTED_GOLDEN_APPLE') },
  { id: 'melon_slice',              label: 'Melon Slice',              categoryHints: ['eat'], icon: I('MELON_SLICE') },
  { id: 'carrot',                   label: 'Carrot',                   categoryHints: ['eat'], icon: I('CARROT') },
  { id: 'potato',                   label: 'Potato',                   categoryHints: ['eat'], icon: I('POTATO') },
  { id: 'beetroot',                 label: 'Beetroot',                 categoryHints: ['eat'], icon: I('BEETROOT') },
  { id: 'mushroom_stew',            label: 'Mushroom Stew',            categoryHints: ['eat'], icon: I('MUSHROOM_STEW') },
  { id: 'suspicious_stew',          label: 'Suspicious Stew',          categoryHints: ['eat'], icon: I('SUSPICIOUS_STEW') },
  { id: 'honey_bottle',             label: 'Honey Bottle',             categoryHints: ['eat'], icon: I('HONEY_BOTTLE') },
  { id: 'chorus_fruit',             label: 'Chorus Fruit',             categoryHints: ['eat'], icon: I('CHORUS_FRUIT') },

  // ── Animals ───────────────────────────────────────────────────────────────
  { id: 'sheep',             label: 'Sheep',             categoryHints: ['animals'],          icon: E('SHEEP') },
  { id: 'white_sheep',       label: 'White Sheep',       categoryHints: ['animals'],          icon: '/mc_assets/WHITE_WOOL.png' },
  { id: 'black_sheep',       label: 'Black Sheep',       categoryHints: ['animals'],          icon: '/mc_assets/BLACK_WOOL.png' },
  { id: 'gray_sheep',        label: 'Gray Sheep',        categoryHints: ['animals'],          icon: '/mc_assets/GRAY_WOOL.png' },
  { id: 'light_gray_sheep',  label: 'Light Gray Sheep',  categoryHints: ['animals'],          icon: '/mc_assets/LIGHT_GRAY_WOOL.png' },
  { id: 'brown_sheep',       label: 'Brown Sheep',       categoryHints: ['animals'],          icon: '/mc_assets/BROWN_WOOL.png' },
  { id: 'red_sheep',         label: 'Red Sheep',         categoryHints: ['animals'],          icon: '/mc_assets/RED_WOOL.png' },
  { id: 'orange_sheep',      label: 'Orange Sheep',      categoryHints: ['animals'],          icon: '/mc_assets/ORANGE_WOOL.png' },
  { id: 'yellow_sheep',      label: 'Yellow Sheep',      categoryHints: ['animals'],          icon: '/mc_assets/YELLOW_WOOL.png' },
  { id: 'lime_sheep',        label: 'Lime Sheep',        categoryHints: ['animals'],          icon: '/mc_assets/LIME_WOOL.png' },
  { id: 'green_sheep',       label: 'Green Sheep',       categoryHints: ['animals'],          icon: '/mc_assets/GREEN_WOOL.png' },
  { id: 'cyan_sheep',        label: 'Cyan Sheep',        categoryHints: ['animals'],          icon: '/mc_assets/CYAN_WOOL.png' },
  { id: 'light_blue_sheep',  label: 'Light Blue Sheep',  categoryHints: ['animals'],          icon: '/mc_assets/LIGHT_BLUE_WOOL.png' },
  { id: 'blue_sheep',        label: 'Blue Sheep',        categoryHints: ['animals'],          icon: '/mc_assets/BLUE_WOOL.png' },
  { id: 'purple_sheep',      label: 'Purple Sheep',      categoryHints: ['animals'],          icon: '/mc_assets/PURPLE_WOOL.png' },
  { id: 'magenta_sheep',     label: 'Magenta Sheep',     categoryHints: ['animals'],          icon: '/mc_assets/MAGENTA_WOOL.png' },
  { id: 'pink_sheep',        label: 'Pink Sheep',        categoryHints: ['animals'],          icon: '/mc_assets/PINK_WOOL.png' },
  { id: 'cow',         label: 'Cow',         categoryHints: ['animals'],          icon: E('COW') },
  { id: 'pig',         label: 'Pig',         categoryHints: ['animals'],          icon: E('PIG') },
  { id: 'chicken',     label: 'Chicken',     categoryHints: ['animals'],          icon: E('CHICKEN') },
  { id: 'rabbit',      label: 'Rabbit',      categoryHints: ['animals'],          icon: E('RABBIT') },
  { id: 'horse',       label: 'Horse',       categoryHints: ['animals', 'ride'],  icon: E('HORSE') },
  { id: 'donkey',      label: 'Donkey',      categoryHints: ['animals', 'ride'],  icon: E('DONKEY') },
  { id: 'mule',        label: 'Mule',        categoryHints: ['animals', 'ride'],  icon: E('MULE') },
  { id: 'wolf',        label: 'Wolf',        categoryHints: ['animals'],          icon: E('WOLF') },
  { id: 'cat',         label: 'Cat',         categoryHints: ['animals'],          icon: E('CAT') },
  { id: 'ocelot',      label: 'Ocelot',      categoryHints: ['animals'],          icon: E('OCELOT') },
  { id: 'parrot',      label: 'Parrot',      categoryHints: ['animals'],          icon: E('PARROT') },
  { id: 'llama',       label: 'Llama',       categoryHints: ['animals', 'ride'],  icon: E('LLAMA') },
  { id: 'cod',         label: 'Cod',         categoryHints: ['animals'],          icon: I('COD') },
  { id: 'salmon',      label: 'Salmon',      categoryHints: ['animals'],          icon: I('SALMON') },
  { id: 'tropical_fish',label: 'Tropical Fish',categoryHints: ['animals'],        icon: I('TROPICAL_FISH') },
  { id: 'pufferfish',  label: 'Pufferfish',  categoryHints: ['animals'],          icon: I('PUFFERFISH') },
  { id: 'fishes',      label: 'Fishes',      categoryHints: ['animals'],          icon: I('COD') },
  { id: 'axolotl',     label: 'Axolotl',     categoryHints: ['animals'],          icon: E('AXOLOTL') },
  { id: 'frog',        label: 'Frog',        categoryHints: ['animals'],          icon: E('FROG') },
  { id: 'turtle',      label: 'Turtle',      categoryHints: ['animals'],          icon: E('TURTLE') },
  { id: 'bee',         label: 'Bee',         categoryHints: ['animals'],          icon: E('BEE') },
  { id: 'fox',         label: 'Fox',         categoryHints: ['animals'],          icon: E('FOX') },
  { id: 'panda',       label: 'Panda',       categoryHints: ['animals'],          icon: E('PANDA') },
  { id: 'polar_bear',  label: 'Polar Bear',  categoryHints: ['animals'],          icon: E('POLAR_BEAR') },
  { id: 'mooshroom',   label: 'Mooshroom',   categoryHints: ['animals'],          icon: E('MOOSHROOM') },
  { id: 'camel',       label: 'Camel',       categoryHints: ['animals', 'ride'],  icon: E('CAMEL') },
  { id: 'sniffer',     label: 'Sniffer',     categoryHints: ['animals'],          icon: E('SNIFFER') },
  { id: 'armadillo',   label: 'Armadillo',   categoryHints: ['animals'],          icon: E('ARMADILLO') },

  // ── Ride ──────────────────────────────────────────────────────────────────
  { id: 'strider',     label: 'Strider',     categoryHints: ['ride'],             icon: E('STRIDER') },
  { id: 'blocks',      label: 'Blocks',      categoryHints: ['ride', 'movement'], icon: I('GRASS_BLOCK') },

  // ── Movement ──────────────────────────────────────────────────────────────
  // surfaces / units used as the "objective" for walk/sprint quests
  { id: 'blocks_walked', label: 'Blocks',     categoryHints: ['movement'],         icon: I('GRASS_BLOCK') },
  { id: 'meters',        label: 'Meters',     categoryHints: ['movement'],         icon: I('GRASS_BLOCK') },
  { id: 'on_ice',        label: 'Ice',        categoryHints: ['movement'],         icon: I('ICE') },
  { id: 'on_packed_ice', label: 'Packed Ice', categoryHints: ['movement'],         icon: I('PACKED_ICE') },
  { id: 'on_blue_ice',   label: 'Blue Ice',   categoryHints: ['movement'],         icon: I('BLUE_ICE') },
  { id: 'on_snow',       label: 'Snow',       categoryHints: ['movement'],         icon: I('SNOW_BLOCK') },
  { id: 'underwater',    label: 'Underwater', categoryHints: ['movement'],         icon: I('WATER_BUCKET') },

  // ── Harvest ───────────────────────────────────────────────────────────────
  { id: 'wheat',         label: 'Wheat',         categoryHints: ['harvest'], icon: I('WHEAT') },
  { id: 'carrot_crop',   label: 'Carrots',        categoryHints: ['harvest'], icon: I('CARROT') },
  { id: 'potato_crop',   label: 'Potatoes',       categoryHints: ['harvest'], icon: I('POTATO') },
  { id: 'beetroot_crop', label: 'Beetroot',       categoryHints: ['harvest'], icon: I('BEETROOT') },
  { id: 'melon',         label: 'Melon',          categoryHints: ['harvest'], icon: I('MELON') },
  { id: 'pumpkin',       label: 'Pumpkin',        categoryHints: ['harvest'], icon: I('PUMPKIN') },
  { id: 'sugar_cane',    label: 'Sugar Cane',     categoryHints: ['harvest'], icon: I('SUGAR_CANE') },
  { id: 'bamboo',        label: 'Bamboo',         categoryHints: ['harvest'], icon: I('BAMBOO') },
  { id: 'cactus',        label: 'Cactus',         categoryHints: ['harvest'], icon: I('CACTUS') },
  { id: 'nether_wart',   label: 'Nether Wart',    categoryHints: ['harvest'], icon: I('NETHER_WART') },
  { id: 'sweet_berries', label: 'Sweet Berries',  categoryHints: ['harvest'], icon: I('SWEET_BERRIES') },
  { id: 'glow_berries',  label: 'Glow Berries',   categoryHints: ['harvest'], icon: I('GLOW_BERRIES') },
  { id: 'torchflower',   label: 'Torchflower',    categoryHints: ['harvest'], icon: I('TORCHFLOWER') },
  { id: 'pitcher_plant', label: 'Pitcher Plant',  categoryHints: ['harvest'], icon: I('PITCHER_PLANT') },

  // ── Workbench ─────────────────────────────────────────────────────────────
  { id: 'enchanted_book',   label: 'Enchanted Book',   categoryHints: ['workbench'],         icon: I('ENCHANTED_BOOK') },
  { id: 'potion',           label: 'Potion',           categoryHints: ['workbench'],         icon: I('POTION') },
  { id: 'splash_potion',    label: 'Splash Potion',    categoryHints: ['workbench'],         icon: I('SPLASH_POTION') },
  { id: 'lingering_potion', label: 'Lingering Potion', categoryHints: ['workbench'],         icon: I('LINGERING_POTION') },
  { id: 'experience_points',label: 'Experience Points',categoryHints: ['workbench', 'kill'], icon: I('EXPERIENCE_BOTTLE') },

  // ── Interact ──────────────────────────────────────────────────────────────
  { id: 'lava_bucket',         label: 'Lava Buckets',        categoryHints: ['interact'],         icon: I('LAVA_BUCKET') },
  { id: 'water_bucket',        label: 'Water Buckets',       categoryHints: ['interact'],         icon: I('WATER_BUCKET') },
  { id: 'powder_snow_bucket',  label: 'Powder Snow Buckets', categoryHints: ['interact'],         icon: I('POWDER_SNOW_BUCKET') },
  { id: 'any_block',           label: 'Blocks',              categoryHints: ['interact', 'mine'], icon: I('GRASS_BLOCK') },
  { id: 'sign',                label: 'Sign',                categoryHints: ['interact'],         icon: I('OAK_SIGN') },
  { id: 'banner',              label: 'Banner',              categoryHints: ['interact'],         icon: I('WHITE_BANNER') },
  { id: 'map',                 label: 'Map',                 categoryHints: ['interact'],         icon: I('MAP') },
  { id: 'book_and_quill',      label: 'Book and Quill',      categoryHints: ['interact'],         icon: I('WRITABLE_BOOK') },
  { id: 'flower_pot',          label: 'Flower Pot',          categoryHints: ['interact'],         icon: I('FLOWER_POT') },
  { id: 'armor_stand',         label: 'Armor Stand',         categoryHints: ['interact'],         icon: I('ARMOR_STAND') },
  { id: 'item_frame',          label: 'Item Frame',          categoryHints: ['interact'],         icon: I('ITEM_FRAME') },
  { id: 'composter',           label: 'Composter',           categoryHints: ['interact'],         icon: I('COMPOSTER') },
  { id: 'cauldron',            label: 'Cauldron',            categoryHints: ['interact'],         icon: I('CAULDRON') },

  // ── Custom / Other ────────────────────────────────────────────────────────
  { id: 'custom', label: 'Other', categoryHints: [], icon: I('BARRIER') },
  { id: 'die', label: 'Times', categoryHints: ['die'], icon: I('BARRIER') },
  { id: 'items', label: 'Items', categoryHints: ['workbench'], icon: I('BOOK') },
]
